package cn.edu.zucc.pb.listfragmentexample.DB;

/**
 * Created by Administrator on 2016/12/23.
 */

public class InputPokemonData {

    public static String Pokemon="[\n" +
            "\t{ \"pid\":\"001\",\t\"zhName\":\"木木枭\",\t\t\"engName\":\"Rowlet\",\t\t\t\"type1\":\"草\",\t\t\"type2\":\"飞行\",\t\t\"ability1\":\"茂盛\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"远隔\",\t\t\t\"hp\":\"68\",\t\t\"atk\":\"55\",\t\t\"def\":\"55\",\t\t\"satk\":\"50\",\t\t\"sdef\":\"50\",\t\t\"speed\":\"42\",\t\t\"profile\":\"不发出一丝声响地滑翔，急速接近敌人。在对方还未发觉时，就使出猛烈的脚踢。\",\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E6%9C%A8%E6%9C%A8%E6%9E%AD\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"002\",\t\"zhName\":\"投羽枭\",\t\t\"engName\":\"Dartrix\",\t\t\"type1\":\"草\",\t\t\"type2\":\"飞行\",\t\t\"ability1\":\"茂盛\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"远隔\",\t\t\t\"hp\":\"78\",\t\t\"atk\":\"75\",\t\t\"def\":\"75\",\t\t\"satk\":\"70\",\t\t\"sdef\":\"70\",\t\t\"speed\":\"52\",\t\t\"profile\":\"将被称为刃羽的锐利羽毛投向敌人和猎物。基本上百发百中。\",\t\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E6%8A%95%E7%BE%BD%E6%9E%AD\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"003\",\t\"zhName\":\"狙射树枭\",\t\"engName\":\"Decidueye\",\t\t\"type1\":\"草\",\t\t\"type2\":\"幽灵\",\t\t\"ability1\":\"茂盛\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"远隔\",\t\t\t\"hp\":\"78\",\t\t\"atk\":\"107\",\t\"def\":\"75\",\t\t\"satk\":\"100\",\t\t\"sdef\":\"100\",\t\t\"speed\":\"70\",\t\t\"profile\":\"基本上是十分谨慎且冷静的，但如果被冷不防地袭击了，就会陷入巨大的恐慌中。\",\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%8B%99%E5%B0%84%E6%A0%91%E6%9E%AD\"\t\t\t},\n" +
            "\t{ \"pid\":\"004\",\t\"zhName\":\"火斑喵\",\t\t\"engName\":\"Litten\",\t\t\t\"type1\":\"火\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"猛火\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"威吓\",\t\t\t\"hp\":\"45\",\t\t\"atk\":\"65\",\t\t\"def\":\"40\",\t\t\"satk\":\"60\",\t\t\"sdef\":\"40\",\t\t\"speed\":\"70\",\t\t\"profile\":\"喜欢不流露感情，独自生活。要取得它的信任，得花点时间。\",\t\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%81%AB%E6%96%91%E5%96%B5\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"005\",\t\"zhName\":\"炎热喵\",\t\t\"engName\":\"Torracat\",\t\t\"type1\":\"火\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"猛火\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"威吓\",\t\t\t\"hp\":\"65\",\t\t\"atk\":\"85\",\t\t\"def\":\"50\",\t\t\"satk\":\"80\",\t\t\"sdef\":\"50\",\t\t\"speed\":\"90\",\t\t\"profile\":\"以前肢的力量而自豪。一记拳击，连铁棒都能弯折。\",\t\t\t\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%82%8E%E7%83%AD%E5%96%B5\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"006\",\t\"zhName\":\"炽焰咆哮虎\",\t\"engName\":\"Incineroar\",\t\t\"type1\":\"火\",\t\t\"type2\":\"恶\",\t\t\"ability1\":\"猛火\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"威吓\",\t\t\t\"hp\":\"95\",\t\t\"atk\":\"115\",\t\"def\":\"90\",\t\t\"satk\":\"80\",\t\t\"sdef\":\"90\",\t\t\"speed\":\"60\",\t\t\"profile\":\"在使出猛烈的拳击或脚踢后，会从肚脐周围喷出火焰，将敌人一击毙命。\",\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%82%BD%E7%84%B0%E5%92%86%E5%93%AE%E8%99%8E\"\t},\n" +
            "\t{ \"pid\":\"007\",\t\"zhName\":\"球球海狮\",\t\"engName\":\"Popplio\",\t\t\"type1\":\"水\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"激流\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"湿润之声\",\t\t\"hp\":\"50\",\t\t\"atk\":\"54\",\t\t\"def\":\"54\",\t\t\"satk\":\"66\",\t\t\"sdef\":\"56\",\t\t\"speed\":\"40\",\t\t\"profile\":\"操纵水做的气球。为了制作大大的球，孜孜不倦地反复练习。\",\t\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%90%83%E7%90%83%E6%B5%B7%E7%8D%85\"\t\t\t},\n" +
            "\t{ \"pid\":\"008\",\t\"zhName\":\"花漾海狮\",\t\"engName\":\"Brionne\",\t\t\"type1\":\"水\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"激流\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"湿润之声\",\t\t\"hp\":\"60\",\t\t\"atk\":\"69\",\t\t\"def\":\"69\",\t\t\"satk\":\"91\",\t\t\"sdef\":\"81\",\t\t\"speed\":\"50\",\t\t\"profile\":\"非常关心自己的伙伴。训练家如果情绪低落，就会跳舞给予鼓励。\",\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E8%8A%B1%E6%BC%BE%E6%B5%B7%E7%8B%AE\"\t\t\t},\n" +
            "\t{ \"pid\":\"009\",\t\"zhName\":\"西狮海壬\",\t\"engName\":\"Primarina\",\t\t\"type1\":\"水\",\t\t\"type2\":\"妖精\",\t\t\"ability1\":\"激流\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"湿润之声\",\t\t\"hp\":\"80\",\t\t\"atk\":\"74\",\t\t\"def\":\"74\",\t\t\"satk\":\"126\",\t\t\"sdef\":\"116\",\t\t\"speed\":\"60\",\t\t\"profile\":\"灵活运用歌声来战斗。每天对嗓子的保养是训练家的重要任务。\",\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E8%A5%BF%E7%8B%AE%E6%B5%B7%E5%A3%AC\"\t\t\t},\n" +
            "\t{ \"pid\":\"010\",\t\"zhName\":\"小笃儿\",\t\t\"engName\":\"Pikipek\",\t\t\"type1\":\"一般\",\t\t\"type2\":\"飞行\",\t\t\"ability1\":\"锐利目光\",\t\t\"ability2\":\"连续攻击\",\t\t\"ability3\":\"捡拾\",\t\t\t\"hp\":\"35\",\t\t\"atk\":\"75\",\t\t\"def\":\"30\",\t\t\"satk\":\"30\",\t\t\"sdef\":\"30\",\t\t\"speed\":\"65\",\t\t\"profile\":\"树果是它的食物。将吃剩下的种子作为子弹从嘴里发射出，用来攻击。\",\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%B0%8F%E7%AC%83%E5%84%BF\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"011\",\t\"zhName\":\"喇叭啄鸟\",\t\"engName\":\"Trumbeak\",\t\t\"type1\":\"一般\",\t\t\"type2\":\"飞行\",\t\t\"ability1\":\"锐利目光\",\t\t\"ability2\":\"连续攻击\",\t\t\"ability3\":\"捡拾\",\t\t\t\"hp\":\"55\",\t\t\"atk\":\"85\",\t\t\"def\":\"50\",\t\t\"satk\":\"40\",\t\t\"sdef\":\"50\",\t\t\"speed\":\"75\",\t\t\"profile\":\"扬起鸟嘴，发出各种叫声。因为相当吵闹，所以周围的居民们很讨厌它。\",\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%96%87%E5%8F%AD%E5%95%84%E9%B8%9F\"\t\t\t},\n" +
            "\t{ \"pid\":\"012\",\t\"zhName\":\"铳嘴大鸟\",\t\"engName\":\"Toucannon\",\t\t\"type1\":\"一般\",\t\t\"type2\":\"飞行\",\t\t\"ability1\":\"锐利目光\",\t\t\"ability2\":\"连续攻击\",\t\t\"ability3\":\"强行\",\t\t\t\"hp\":\"80\",\t\t\"atk\":\"120\",\t\"def\":\"75\",\t\t\"satk\":\"75\",\t\t\"sdef\":\"75\",\t\t\"speed\":\"60\",\t\t\"profile\":\"让体内的气体在嘴里爆发，发射出树果的种子。是连巨大岩石也能粉碎的力量。\",\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E9%93%B3%E5%98%B4%E5%A4%A7%E9%B8%9F\"\t\t\t},\n" +
            "\t{ \"pid\":\"013\",\t\"zhName\":\"猫鼬少\",\t\t\"engName\":\"Yungoos\",\t\t\"type1\":\"一般\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"蹲守\",\t\t\t\"ability2\":\"强壮之颚\",\t\t\"ability3\":\"适应力\",\t\t\"hp\":\"48\",\t\t\"atk\":\"70\",\t\t\"def\":\"30\",\t\t\"satk\":\"30\",\t\t\"sdef\":\"30\",\t\t\"speed\":\"45\",\t\t\"profile\":\"不断巡回着寻找食物。到了太阳落山的时候，因为精疲力尽而一头栽倒就这么睡着。\",\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%8C%AB%E9%BC%AC%E5%B0%91\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"014\",\t\"zhName\":\"猫鼬探长\",\t\"engName\":\"Gumshoos\",\t\t\"type1\":\"一般\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"蹲守\",\t\t\t\"ability2\":\"强壮之颚\",\t\t\"ability3\":\"适应力\",\t\t\"hp\":\"88\",\t\t\"atk\":\"110\",\t\"def\":\"60\",\t\t\"satk\":\"55\",\t\t\"sdef\":\"60\",\t\t\"speed\":\"45\",\t\t\"profile\":\"喜欢吃小拉达和拉达，但因为昼行性而无法遇到。是以忍耐力强而自豪的宝可梦。\",\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%8C%AB%E9%BC%AC%E6%8E%A2%E9%95%BF\"\t\t\t},\n" +
            "\t{ \"pid\":\"015\",\t\"zhName\":\"小拉达\",\t\t\"engName\":\"Rattata\",\t\t\"type1\":\"恶\",\t\t\"type2\":\"一般\",\t\t\"ability1\":\"逃跑\",\t\t\t\"ability2\":\"毅力\",\t\t\t\"ability3\":\"活力\",\t\t\t\"hp\":\"30\",\t\t\"atk\":\"56\",\t\t\"def\":\"35\",\t\t\"satk\":\"25\",\t\t\"sdef\":\"35\",\t\t\"speed\":\"72\",\t\t\"profile\":\"生命力很强，即使在肮脏的地方也能坦然生活。放任不管的话会不停繁殖。\",\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%B0%8F%E6%8B%89%E8%BE%BE\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"016\",\t\"zhName\":\"拉达\",\t\t\"engName\":\"Raticate\",\t\t\"type1\":\"恶\",\t\t\"type2\":\"一般\",\t\t\"ability1\":\"逃跑\",\t\t\t\"ability2\":\"毅力\",\t\t\t\"ability3\":\"活力\",\t\t\t\"hp\":\"55\",\t\t\"atk\":\"81\",\t\t\"def\":\"60\",\t\t\"satk\":\"50\",\t\t\"sdef\":\"70\",\t\t\"speed\":\"97\",\t\t\"profile\":\"性格比外表看起来凶残得多。如果把手伸到面前，或许会被一口咬断。\",\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E6%8B%89%E8%BE%BE\"\t\t\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"017\",\t\"zhName\":\"绿毛虫\",\t\t\"engName\":\"Caterpie\",\t\t\"type1\":\"虫\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"鳞粉\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"逃跑\",\t\t\t\"hp\":\"45\",\t\t\"atk\":\"30\",\t\t\"def\":\"35\",\t\t\"satk\":\"20\",\t\t\"sdef\":\"20\",\t\t\"speed\":\"45\",\t\t\"profile\":\"易于捕捉，成长也快。是推荐给新手训练家作为同伴的宝可梦之一。\",\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%BB%BF%E6%AF%9B%E8%99%AB\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"018\",\t\"zhName\":\"铁甲蛹\",\t\t\"engName\":\"Metapod\",\t\t\"type1\":\"虫\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"蜕皮\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"无\",\t\t\t\"hp\":\"50\",\t\t\"atk\":\"20\",\t\t\"def\":\"55\",\t\t\"satk\":\"25\",\t\t\"sdef\":\"25\",\t\t\"speed\":\"30\",\t\t\"profile\":\"虽说坚硬，但还是虫的外壳。因为有时也会破裂，所以禁止用于激烈的战斗。\",\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E9%93%81%E7%94%B2%E8%9B%B9\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"019\",\t\"zhName\":\"巴大蝶\",\t\t\"engName\":\"Butterfree\",\t\t\"type1\":\"虫\",\t\t\"type2\":\"飞行\",\t\t\"ability1\":\"复眼\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"有色眼镜\",\t\t\"hp\":\"60\",\t\t\"atk\":\"45\",\t\t\"def\":\"50\",\t\t\"satk\":\"90\",\t\t\"sdef\":\"80\",\t\t\"speed\":\"70\",\t\t\"profile\":\"如果被其他宝可梦袭击，就会一边挥洒有毒的鳞粉，一边拍动翅膀抵抗。\",\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%B7%B4%E5%A4%A7%E8%9D%B6\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"020\",\t\"zhName\":\"芭瓢虫\",\t\t\"engName\":\"Ledyba\",\t\t\t\"type1\":\"虫\",\t\t\"type2\":\"飞行\",\t\t\"ability1\":\"虫之预感\",\t\t\"ability2\":\"早起\",\t\t\t\"ability3\":\"胆怯\",\t\t\t\"hp\":\"40\",\t\t\"atk\":\"20\",\t\t\"def\":\"30\",\t\t\"satk\":\"40\",\t\t\"sdef\":\"80\",\t\t\"speed\":\"55\",\t\t\"profile\":\"用带气味的体液与伙伴交流。发怒的时候，气味会酸酸的\",\t\t\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E8%8A%AD%E7%93%A2%E8%99%AB\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"021\",\t\"zhName\":\"安瓢虫\",\t\t\"engName\":\"Ledian\",\t\t\t\"type1\":\"虫\",\t\t\"type2\":\"飞行\",\t\t\"ability1\":\"虫之预感\",\t\t\"ability2\":\"早起\",\t\t\t\"ability3\":\"铁拳\",\t\t\t\"hp\":\"55\",\t\t\"atk\":\"35\",\t\t\"def\":\"50\",\t\t\"satk\":\"55\",\t\t\"sdef\":\"110\",\t\t\"speed\":\"85\",\t\t\"profile\":\"用４条手臂挥拳战斗。一拳的威力并不怎么样，但依靠出拳数取胜。\",\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%AE%89%E7%93%A2%E8%99%AB\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"022\",\t\"zhName\":\"圆丝蛛\",\t\t\"engName\":\"Spinarak\",\t\t\"type1\":\"虫\",\t\t\"type2\":\"毒\",\t\t\"ability1\":\"虫之预感\",\t\t\"ability2\":\"不眠\",\t\t\t\"ability3\":\"狙击手\",\t\t\"hp\":\"40\",\t\t\"atk\":\"60\",\t\t\"def\":\"40\",\t\t\"satk\":\"40\",\t\t\"sdef\":\"40\",\t\t\"speed\":\"30\",\t\t\"profile\":\"有些渔夫会用其坚韧的丝，编织制作成可以捕捉鱼宝可梦的网。\",\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%9C%86%E4%B8%9D%E8%9B%9B\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"023\",\t\"zhName\":\"阿利多斯\",\t\"engName\":\"Ariados\",\t\t\"type1\":\"虫\",\t\t\"type2\":\"毒\",\t\t\"ability1\":\"虫之预感\",\t\t\"ability2\":\"不眠\",\t\t\t\"ability3\":\"狙击手\",\t\t\"hp\":\"70\",\t\t\"atk\":\"90\",\t\t\"def\":\"70\",\t\t\"satk\":\"60\",\t\t\"sdef\":\"70\",\t\t\"speed\":\"40\",\t\t\"profile\":\"屁股和嘴里都会吐出丝。用丝绑住猎物，慢慢地吸食它的体液。\",\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E9%98%BF%E5%88%A9%E5%A4%9A%E6%96%AF\"\t\t\t},\n" +
            "\t{ \"pid\":\"024\",\t\"zhName\":\"皮丘\",\t\t\"engName\":\"Pichu\",\t\t\t\"type1\":\"电\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"静电\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"避雷针\",\t\t\"hp\":\"20\",\t\t\"atk\":\"40\",\t\t\"def\":\"15\",\t\t\"satk\":\"35\",\t\t\"sdef\":\"35\",\t\t\"speed\":\"60\",\t\t\"profile\":\"虽然很可爱，但如果一起生活的话，就必须有被电击电得麻麻的觉悟。\",\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%9A%AE%E4%B8%98\"\t\t\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"025\",\t\"zhName\":\"皮卡丘\",\t\t\"engName\":\"Pikachu\",\t\t\"type1\":\"电\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"静电\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"避雷针\",\t\t\"hp\":\"35\",\t\t\"atk\":\"55\",\t\t\"def\":\"40\",\t\t\"satk\":\"50\",\t\t\"sdef\":\"50\",\t\t\"speed\":\"90\",\t\t\"profile\":\"有积聚电力的特质。不时常尽情释放电力的话，就会倍感压力。\",\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%9A%AE%E5%8D%A1%E4%B8%98\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"026\",\t\"zhName\":\"雷丘\",\t\t\"engName\":\"Raichu\",\t\t\t\"type1\":\"电\",\t\t\"type2\":\"超能力\",\t\"ability1\":\"静电\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"避雷针\",\t\t\"hp\":\"60\",\t\t\"atk\":\"90\",\t\t\"def\":\"55\",\t\t\"satk\":\"90\",\t\t\"sdef\":\"80\",\t\t\"speed\":\"110\",\t\t\"profile\":\"电力积聚的话，脾气就会变坏。即便是训练家，一不留神也会被袭击。\",\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E9%9B%B7%E4%B8%98\"\t\t\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"027\",\t\"zhName\":\"强颚鸡母虫\",\t\"engName\":\"Grubbin\",\t\t\"type1\":\"虫\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"虫之预感\",\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"无\",\t\t\t\"hp\":\"47\",\t\t\"atk\":\"62\",\t\t\"def\":\"45\",\t\t\"satk\":\"55\",\t\t\"sdef\":\"45\",\t\t\"speed\":\"46\",\t\t\"profile\":\"为了不被鸟宝可梦袭击，经常聚集在电属性宝可梦栖息的地方。\",\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%BC%BA%E9%A2%9A%E9%B8%A1%E6%AF%8D%E8%99%AB\"\t},\n" +
            "\t{ \"pid\":\"028\",\t\"zhName\":\"虫电宝\",\t\t\"engName\":\"Charjabug\",\t\t\"type1\":\"虫\",\t\t\"type2\":\"电\",\t\t\"ability1\":\"蓄电池\",\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"无\",\t\t\t\"hp\":\"57\",\t\t\"atk\":\"82\",\t\t\"def\":\"95\",\t\t\"satk\":\"55\",\t\t\"sdef\":\"75\",\t\t\"speed\":\"36\",\t\t\"profile\":\"会将消化吃下的食物时所产生的电能储藏在电力袋中。\",\t\t\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E8%99%AB%E7%94%B5%E5%AE%9D\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"029\",\t\"zhName\":\"锹农炮虫\",\t\"engName\":\"Vikavolt\",\t\t\"type1\":\"虫\",\t\t\"type2\":\"电\",\t\t\"ability1\":\"飘浮\",\t\t\t\"ability2\":\"无\",\t\t\t\"ability3\":\"无\",\t\t\t\"hp\":\"77\",\t\t\"atk\":\"70\",\t\t\"def\":\"90\",\t\t\"satk\":\"145\",\t\t\"sdef\":\"75\",\t\t\"speed\":\"43\",\t\t\"profile\":\"用位于腹部的发电器官发出电力。即便是鸟宝可梦也能被它用电击光束压制。\",\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E9%94%B9%E5%86%9C%E7%82%AE%E8%99%AB\"\t\t\t},\n" +
            "\t{ \"pid\":\"030\",\t\"zhName\":\"盆才怪\",\t\t\"engName\":\"Bonsly\",\t\t\t\"type1\":\"岩石\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"结实\",\t\t\t\"ability2\":\"坚硬脑袋\",\t\t\"ability3\":\"胆怯\",\t\t\t\"hp\":\"50\",\t\t\"atk\":\"80\",\t\t\"def\":\"95\",\t\t\"satk\":\"10\",\t\t\"sdef\":\"45\",\t\t\"speed\":\"10\",\t\t\"profile\":\"会从眼睛排出体内多余的水分。该成分接近人类的汗液。\",\t\t\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%9B%86%E6%89%8D%E6%80%AA\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"031\",\t\"zhName\":\"树才怪\",\t\t\"engName\":\"Sudowoodo\",\t\t\"type1\":\"岩石\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"结实\",\t\t\t\"ability2\":\"坚硬脑袋\",\t\t\"ability3\":\"胆怯\",\t\t\t\"hp\":\"70\",\t\t\"atk\":\"100\",\t\"def\":\"115\",\t\"satk\":\"30\",\t\t\"sdef\":\"65\",\t\t\"speed\":\"30\",\t\t\"profile\":\"在老年人当中很受欢迎。听说绿色的部分越大，爱好者们的评价就越高。\",\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E6%A0%91%E6%89%8D%E6%80%AA\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"032\",\t\"zhName\":\"小福蛋\",\t\t\"engName\":\"Happiny\",\t\t\"type1\":\"一般\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"自然回复\",\t\t\"ability2\":\"天恩\",\t\t\t\"ability3\":\"友情防守\",\t\t\"hp\":\"100\",\t\t\"atk\":\"5\",\t\t\"def\":\"5\",\t\t\"satk\":\"15\",\t\t\"sdef\":\"65\",\t\t\"speed\":\"30\",\t\t\"profile\":\"因为很小，还不能生蛋。会寻找白白的圆圆的石头来作为替代。\",\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%B0%8F%E7%A6%8F%E8%9B%8B\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"033\",\t\"zhName\":\"吉利蛋\",\t\t\"engName\":\"Chansey\",\t\t\"type1\":\"一般\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"自然回复\",\t\t\"ability2\":\"天恩\",\t\t\t\"ability3\":\"治愈之心\",\t\t\"hp\":\"250\",\t\t\"atk\":\"5\",\t\t\"def\":\"5\",\t\t\"satk\":\"35\",\t\t\"sdef\":\"105\",\t\t\"speed\":\"50\",\t\t\"profile\":\"因为是数量稀少而且逃跑很快的宝可梦，所以能找到它的人运气相当不错。\",\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%90%89%E5%88%A9%E8%9B%8B\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"034\",\t\"zhName\":\"幸福蛋\",\t\t\"engName\":\"Bissey\",\t\t\t\"type1\":\"一般\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"自然回复\",\t\t\"ability2\":\"天恩\",\t\t\t\"ability3\":\"治愈之心\",\t\t\"hp\":\"255\",\t\t\"atk\":\"10\",\t\t\"def\":\"10\",\t\t\"satk\":\"75\",\t\t\"sdef\":\"135\",\t\t\"speed\":\"55\",\t\t\"profile\":\"蓬松的体毛是感应器。可以捕捉到宝可梦和人类的心情。\",\t\t\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%B9%B8%E7%A6%8F%E8%9B%8B\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"035\",\t\"zhName\":\"小卡比兽\",\t\"engName\":\"Munchlax\",\t\t\"type1\":\"一般\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"捡拾\",\t\t\t\"ability2\":\"厚脂肪\",\t\t\"ability3\":\"贪吃鬼\",\t\t\"hp\":\"135\",\t\t\"atk\":\"85\",\t\t\"def\":\"40\",\t\t\"satk\":\"40\",\t\t\"sdef\":\"85\",\t\t\"speed\":\"5\",\t\t\"profile\":\"一旦找到看起来能吃的东西，就不管三七二十一先捡起来吞了。所以就这么一天天地变胖起来。\",\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%B0%8F%E5%8D%A1%E6%AF%94%E5%85%BD\"\t\t\t},\n" +
            "\t{ \"pid\":\"036\",\t\"zhName\":\"卡比兽\",\t\t\"engName\":\"Snorlax\",\t\t\"type1\":\"一般\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"免疫\",\t\t\t\"ability2\":\"厚脂肪\",\t\t\"ability3\":\"贪吃鬼\",\t\t\"hp\":\"160\",\t\t\"atk\":\"110\",\t\"def\":\"65\",\t\t\"satk\":\"65\",\t\t\"sdef\":\"110\",\t\t\"speed\":\"30\",\t\t\"profile\":\"每天要吃下４００公斤的食物。开吃之后，就会开始打瞌睡，即使是睡着的状态也会继续吃。\",\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%8D%A1%E6%AF%94%E5%85%BD\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"037\",\t\"zhName\":\"呆呆兽\",\t\t\"engName\":\"Slowpoke\",\t\t\"type1\":\"水\",\t\t\"type2\":\"超能力\",\t\"ability1\":\"迟钝\",\t\t\t\"ability2\":\"我行我素\",\t\t\"ability3\":\"再生力\",\t\t\"hp\":\"90\",\t\t\"atk\":\"65\",\t\t\"def\":\"65\",\t\t\"satk\":\"40\",\t\t\"sdef\":\"40\",\t\t\"speed\":\"15\",\t\t\"profile\":\"把呆呆兽的尾巴晒干后再用盐水煮成的小菜，是阿罗拉的家常美味。\",\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%91%86%E5%91%86%E5%85%BD\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"038\",\t\"zhName\":\"呆壳兽\",\t\t\"engName\":\"Slowbro\",\t\t\"type1\":\"水\",\t\t\"type2\":\"超能力\",\t\"ability1\":\"迟钝\",\t\t\t\"ability2\":\"我行我素\",\t\t\"ability3\":\"再生力\",\t\t\"hp\":\"95\",\t\t\"atk\":\"75\",\t\t\"def\":\"110\",\t\"satk\":\"100\",\t\t\"sdef\":\"80\",\t\t\"speed\":\"30\",\t\t\"profile\":\"每次大舌贝狠狠咬下去的瞬间会有什么在脑海中闪过，但转瞬之间就全部忘光了。\",\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%91%86%E5%A3%B3%E5%85%BD\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"039\",\t\"zhName\":\"呆呆王\",\t\t\"engName\":\"Slowking\",\t\t\"type1\":\"水\",\t\t\"type2\":\"超能力\",\t\"ability1\":\"迟钝\",\t\t\t\"ability2\":\"我行我素\",\t\t\"ability3\":\"再生力\",\t\t\"hp\":\"95\",\t\t\"atk\":\"75\",\t\t\"def\":\"80\",\t\t\"satk\":\"100\",\t\t\"sdef\":\"110\",\t\t\"speed\":\"30\",\t\t\"profile\":\"迷路就问呆呆王，也有地区流传着这样的俗语，可见它因聪明而广为人知。\",\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%91%86%E5%91%86%E7%8E%8B\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"040\",\t\"zhName\":\"长翅鸥\",\t\t\"engName\":\"Wingull\",\t\t\"type1\":\"水\",\t\t\"type2\":\"飞行\",\t\t\"ability1\":\"锐利目光\",\t\t\"ability2\":\"湿润之躯\",\t\t\"ability3\":\"雨盘\",\t\t\t\"hp\":\"40\",\t\t\"atk\":\"30\",\t\t\"def\":\"30\",\t\t\"satk\":\"55\",\t\t\"sdef\":\"30\",\t\t\"speed\":\"85\",\t\t\"profile\":\"在长翅鸥飞来飞去的海下面聚集着成群的鱼宝可梦，所以渔夫会先寻找长翅鸥。\",\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E9%95%BF%E7%BF%85%E9%B8%A5\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"041\",\t\"zhName\":\"大嘴鸥\",\t\t\"engName\":\"Pelipper\",\t\t\"type1\":\"水\",\t\t\"type2\":\"飞行\",\t\t\"ability1\":\"锐利目光\",\t\t\"ability2\":\"降雨\",\t\t\t\"ability3\":\"雨盘\",\t\t\t\"hp\":\"60\",\t\t\"atk\":\"50\",\t\t\"def\":\"100\",\t\"satk\":\"95\",\t\t\"sdef\":\"70\",\t\t\"speed\":\"65\",\t\t\"profile\":\"收集食物是年轻♂的活儿。在大大的鸟嘴里储藏食物，运送到伙伴等待的巢穴中。\",\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%A4%A7%E5%98%B4%E9%B8%A5\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"042\",\t\"zhName\":\"凯西\",\t\t\"engName\":\"Abra\",\t\t\t\"type1\":\"超能力\",\t\"type2\":\"无\",\t\t\"ability1\":\"同步\",\t\t\t\"ability2\":\"精神力\",\t\t\"ability3\":\"魔法防守\",\t\t\"hp\":\"25\",\t\t\"atk\":\"20\",\t\t\"def\":\"15\",\t\t\"satk\":\"105\",\t\t\"sdef\":\"55\",\t\t\"speed\":\"90\",\t\t\"profile\":\"即使是睡着的时候也会用瞬间移动保护身体，但醒来时会因不知自己在何处而慌张。\",\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%87%AF%E8%A5%BF\"\t\t\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"043\",\t\"zhName\":\"勇基拉\",\t\t\"engName\":\"Kadabra\",\t\t\"type1\":\"超能力\",\t\"type2\":\"无\",\t\t\"ability1\":\"同步\",\t\t\t\"ability2\":\"精神力\",\t\t\"ability3\":\"魔法防守\",\t\t\"hp\":\"40\",\t\t\"atk\":\"35\",\t\t\"def\":\"30\",\t\t\"satk\":\"120\",\t\t\"sdef\":\"70\",\t\t\"speed\":\"105\",\t\t\"profile\":\"勇基拉在的时候，电视机等机械的显示器中会有召唤不幸的可怕影像闪现\",\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%8B%87%E5%9F%BA%E6%8B%89\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"044\",\t\"zhName\":\"胡地\",\t\t\"engName\":\"Alakazam\",\t\t\"type1\":\"超能力\",\t\"type2\":\"无\",\t\t\"ability1\":\"同步\",\t\t\t\"ability2\":\"精神力\",\t\t\"ability3\":\"魔法防守\",\t\t\"hp\":\"55\",\t\t\"atk\":\"50\",\t\t\"def\":\"45\",\t\t\"satk\":\"135\",\t\t\"sdef\":\"95\",\t\t\"speed\":\"120\",\t\t\"profile\":\"脑细胞会终生不断增长。越是年老的胡地越是会有巨大的脑袋。\",\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E8%83%A1%E5%9C%B0\"\t\t\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"045\",\t\"zhName\":\"喵喵\",\t\t\"engName\":\"Meowth\",\t\t\t\"type1\":\"恶\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"捡拾\",\t\t\t\"ability2\":\"技术高手\",\t\t\"ability3\":\"紧张感\",\t\t\"hp\":\"40\",\t\t\"atk\":\"45\",\t\t\"def\":\"35\",\t\t\"satk\":\"40\",\t\t\"sdef\":\"40\",\t\t\"speed\":\"90\",\t\t\"profile\":\"非常喜欢闪闪亮亮的东西。经常和黑暗鸦为了争夺猎物而打架。\",\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%96%B5%E5%96%B5\"\t\t\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"046\",\t\"zhName\":\"猫老大\",\t\t\"engName\":\"Prsian\",\t\t\t\"type1\":\"恶\",\t\t\"type2\":\"无\",\t\t\"ability1\":\"柔软\",\t\t\t\"ability2\":\"技术高手\",\t\t\"ability3\":\"紧张感\",\t\t\"hp\":\"65\",\t\t\"atk\":\"70\",\t\t\"def\":\"60\",\t\t\"satk\":\"65\",\t\t\"sdef\":\"65\",\t\t\"speed\":\"115\",\t\t\"profile\":\"还没有达到阿罗拉的猫老大的地位，但是性情傲慢自大。要和它变得亲密相当困难。\",\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E7%8C%AB%E8%80%81%E5%A4%A7\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"047\",\t\"zhName\":\"小磁怪\",\t\t\"engName\":\"Magbemite\",\t\t\"type1\":\"电\",\t\t\"type2\":\"钢\",\t\t\"ability1\":\"磁力\",\t\t\t\"ability2\":\"结实\",\t\t\t\"ability3\":\"分析\",\t\t\t\"hp\":\"25\",\t\t\"atk\":\"35\",\t\t\"def\":\"70\",\t\t\"satk\":\"95\",\t\t\"sdef\":\"55\",\t\t\"speed\":\"45\",\t\t\"profile\":\"释放出电磁波，在空中飘浮。如果在吞食电力的时候触碰它，就会全身被电得噼里啪啦的。\",\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E5%B0%8F%E7%A3%81%E6%80%AA\"\t\t\t\t\t},\n" +
            "\t{ \"pid\":\"048\",\t\"zhName\":\"三合一磁怪\",\t\"engName\":\"Magbeton\",\t\t\"type1\":\"电\",\t\t\"type2\":\"钢\",\t\t\"ability1\":\"磁力\",\t\t\t\"ability2\":\"结实\",\t\t\t\"ability3\":\"分析\",\t\t\t\"hp\":\"50\",\t\t\"atk\":\"60\",\t\t\"def\":\"95\",\t\t\"satk\":\"120\",\t\t\"sdef\":\"70\",\t\t\"speed\":\"70\",\t\t\"profile\":\"大约有小磁怪３倍的电力。不知为何会在太阳黑子多的时候大量出现。\",\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E4%B8%89%E5%90%88%E4%B8%80%E7%A3%81%E6%80%AA\"\t},\n" +
            "\t{ \"pid\":\"049\",\t\"zhName\":\"自爆磁怪\",\t\"engName\":\"Magnezone\",\t\t\"type1\":\"电\",\t\t\"type2\":\"钢\",\t\t\"ability1\":\"磁力\",\t\t\t\"ability2\":\"结实\",\t\t\t\"ability3\":\"分析\",\t\t\t\"hp\":\"70\",\t\t\"atk\":\"70\",\t\t\"def\":\"115\",\t\"satk\":\"130\",\t\t\"sdef\":\"90\",\t\t\"speed\":\"60\",\t\t\"profile\":\"据说会一边在空中来回飞行，一边发送怪异电波和接收未知电波。\",\t\t\t\t\t\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E8%87%AA%E7%88%86%E7%A3%81%E6%80%AA\"\t\t\t},\n" +
            "\t{ \"pid\":\"050\",\t\"zhName\":\"臭泥\",\t\t\"engName\":\"Grimer\",\t\t\t\"type1\":\"毒\",\t\t\"type2\":\"恶\",\t\t\"ability1\":\"恶臭\",\t\t\t\"ability2\":\"黏着\",\t\t\t\"ability3\":\"毒手\",\t\t\t\"hp\":\"80\",\t\t\"atk\":\"80\",\t\t\"def\":\"50\",\t\t\"satk\":\"40\",\t\t\"sdef\":\"50\",\t\t\"speed\":\"25\",\t\t\"profile\":\"污泥沐浴了来自月亮的Ｘ射线后，发生变化而诞生的。身体的细菌如果减少就会死亡。\",\t\t\t\t\"link\":\"https://wiki.52poke.com/wiki/%E8%87%AD%E6%B3%A5\"\t\t\t\t\t\t\t},\n" +
            "]";

//    public static String EvolveLine="[\n" +
//            "\t{\"eid\":\"1\",\t\"etype1\":\"001\",\t\"etype2\":\"002\",\t\"etype3\":\"003\"},\n" +
//            "\t{\"eid\":\"2\",\t\"etype1\":\"004\",\t\"etype2\":\"005\",\t\"etype3\":\"006\"},\n" +
//            "\t{\"eid\":\"3\",\t\"etype1\":\"007\",\t\"etype2\":\"008\",\t\"etype3\":\"009\"},\n" +
//            "\t{\"eid\":\"4\",\t\"etype1\":\"010\",\t\"etype2\":\"011\",\t\"etype3\":\"012\"},\n" +
//            "\t{\"eid\":\"5\",\t\"etype1\":\"013\",\t\"etype2\":\"014\",\t\"etype3\":\"无\"},\n" +
//            "\t{\"eid\":\"6\",\t\"etype1\":\"015\",\t\"etype2\":\"016\",\t\"etype3\":\"无\"},\n" +
//            "\t{\"eid\":\"7\",\t\"etype1\":\"017\",\t\"etype2\":\"018\",\t\"etype3\":\"019\"},\n" +
//            "\t{\"eid\":\"8\",\t\"etype1\":\"020\",\t\"etype2\":\"021\",\t\"etype3\":\"无\"},\n" +
//            "\t{\"eid\":\"9\",\t\"etype1\":\"022\",\t\"etype2\":\"023\",\t\"etype3\":\"无\"},\n" +
//            "\t{\"eid\":\"10\",\t\"etype1\":\"024\",\t\"etype2\":\"025\",\t\"etype3\":\"026\"},\n" +
//            "\t{\"eid\":\"11\",\t\"etype1\":\"027\",\t\"etype2\":\"028\",\t\"etype3\":\"029\"},\n" +
//            "\t{\"eid\":\"12\",\t\"etype1\":\"030\",\t\"etype2\":\"031\",\t\"etype3\":\"无\"},\n" +
//            "\t{\"eid\":\"13\",\t\"etype1\":\"032\",\t\"etype2\":\"033\",\t\"etype3\":\"034\"},\n" +
//            "\t{\"eid\":\"14\",\t\"etype1\":\"035\",\t\"etype2\":\"036\",\t\"etype3\":\"无\"},\n" +
//            "\t{\"eid\":\"15\",\t\"etype1\":\"037\",\t\"etype2\":\"038\",\t\"etype3\":\"无\"},\n" +
//            "\t{\"eid\":\"16\",\t\"etype1\":\"037\",\t\"etype2\":\"039\",\t\"etype3\":\"无\"},\n" +
//            "\t{\"eid\":\"17\",\t\"etype1\":\"040\",\t\"etype2\":\"041\",\t\"etype3\":\"无\"},\n" +
//            "\t{\"eid\":\"18\",\t\"etype1\":\"042\",\t\"etype2\":\"043\",\t\"etype3\":\"044\"},\n" +
//            "\t{\"eid\":\"19\",\t\"etype1\":\"045\",\t\"etype2\":\"046\",\t\"etype3\":\"无\"},\n" +
//            "\t{\"eid\":\"20\",\t\"etype1\":\"047\",\t\"etype2\":\"048\",\t\"etype3\":\"049\"},\n" +
//            "\t{\"eid\":\"21\",\t\"etype1\":\"050\",\t\"etype2\":\"088\",\t\"etype3\":\"无\"}\n" +
//            "]";

    public static String EvolveLine=" [\n" +
            "\t{\"eid\":\"1\",\t\t\"etype1\":\"木木枭\",\t\t\"etype2\":\"投羽枭\",\t\t\"etype3\":\"狙射树枭\"},\n" +
            "\t{\"eid\":\"2\",\t\t\"etype1\":\"火斑喵\",\t\t\"etype2\":\"炎热喵\",\t\t\"etype3\":\"炽焰咆哮虎\"},\n" +
            "\t{\"eid\":\"3\",\t\t\"etype1\":\"球球海狮\",\t\"etype2\":\"花漾海狮\",\t\"etype3\":\"西狮海壬\"},\n" +
            "\t{\"eid\":\"4\",\t\t\"etype1\":\"小笃儿\",\t\t\"etype2\":\"喇叭啄鸟\",\t\"etype3\":\"铳嘴大鸟\"},\n" +
            "\t{\"eid\":\"5\",\t\t\"etype1\":\"猫鼬少\",\t\t\"etype2\":\"猫鼬探长\",\t\"etype3\":\"无\"},\n" +
            "\t{\"eid\":\"6\",\t\t\"etype1\":\"小拉达\",\t\t\"etype2\":\"拉达\",\t\t\"etype3\":\"无\"},\n" +
            "\t{\"eid\":\"7\",\t\t\"etype1\":\"绿毛虫\",\t\t\"etype2\":\"铁甲蛹\",\t\t\"etype3\":\"巴大蝶\"},\n" +
            "\t{\"eid\":\"8\",\t\t\"etype1\":\"芭瓢虫\",\t\t\"etype2\":\"安瓢虫\",\t\t\"etype3\":\"无\"},\n" +
            "\t{\"eid\":\"9\",\t\t\"etype1\":\"圆丝蛛\",\t\t\"etype2\":\"阿利多斯\",\t\"etype3\":\"无\"},\n" +
            "\t{\"eid\":\"10\",\t\"etype1\":\"皮丘\",\t\t\"etype2\":\"皮卡丘\",\t\t\"etype3\":\"雷丘\"},\n" +
            "\t{\"eid\":\"11\",\t\"etype1\":\"强颚鸡母虫\",\t\"etype2\":\"虫电宝\",\t\t\"etype3\":\"锹农炮虫\"},\n" +
            "\t{\"eid\":\"12\",\t\"etype1\":\"盆才怪\",\t\t\"etype2\":\"树才怪\",\t\t\"etype3\":\"无\"},\n" +
            "\t{\"eid\":\"13\",\t\"etype1\":\"小福蛋\",\t\t\"etype2\":\"吉利蛋\",\t\t\"etype3\":\"幸福蛋\"},\n" +
            "\t{\"eid\":\"14\",\t\"etype1\":\"小卡比兽\",\t\"etype2\":\"卡比兽\",\t\t\"etype3\":\"无\"},\n" +
            "\t{\"eid\":\"15\",\t\"etype1\":\"呆呆兽\",\t\t\"etype2\":\"呆壳兽\",\t\t\"etype3\":\"无\"},\n" +
            "\t{\"eid\":\"16\",\t\"etype1\":\"呆呆兽\",\t\t\"etype2\":\"呆呆王\",\t\t\"etype3\":\"无\"},\n" +
            "\t{\"eid\":\"17\",\t\"etype1\":\"长翅鸥\",\t\t\"etype2\":\"大嘴鸥\",\t\t\"etype3\":\"无\"},\n" +
            "\t{\"eid\":\"18\",\t\"etype1\":\"凯西\",\t\t\"etype2\":\"勇基拉\",\t\t\"etype3\":\"胡地\"},\n" +
            "\t{\"eid\":\"19\",\t\"etype1\":\"喵喵\",\t\t\"etype2\":\"猫老大\",\t\t\"etype3\":\"无\"},\n" +
            "\t{\"eid\":\"20\",\t\"etype1\":\"小磁怪\",\t\t\"etype2\":\"三合一磁怪\",\t\"etype3\":\"自爆磁怪\"},\n" +
            "\t{\"eid\":\"21\",\t\"etype1\":\"臭泥\",\t\t\"etype2\":\"臭臭泥\",\t\t\"etype3\":\"无\"}\n" +
            "]";




}
